export const commilint = [
  '✨ feat:commit message',
  '🐛 fix:commit message',
  '📝 docs:commit message',
  '💄 style:commit message',
  '♻️ refactor:commit message',
  '⚡️ perf:commit message',
  '✅ test:commit message',
  '📦 build:commit message',
  '👷 ci:commit message',
  '🔒 security:commit message',
  '⬆️ upgrade:commit message',
  '⬇️ downgrade:commit message',
  '🚀 chore:commit message',
  '🔥 remove:commit message',
];
